{"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/Iden3\/documentation\/Iden3\/NetworkError\/localizedDescription"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError\/Error-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/Iden3\/documentation\/Iden3","doc:\/\/Iden3\/documentation\/Iden3\/NetworkError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iden3\/networkerror\/error-implementations"]}],"metadata":{"title":"Error Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"Iden3"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://Iden3/documentation/Iden3":{"title":"Iden3","identifier":"doc:\/\/Iden3\/documentation\/Iden3","kind":"symbol","role":"collection","url":"\/documentation\/iden3","abstract":[],"type":"topic"},"doc://Iden3/documentation/Iden3/NetworkError":{"title":"NetworkError","type":"topic","abstract":[{"type":"text","text":"An error performing a network call"}],"navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"identifier":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkError"}],"kind":"symbol","url":"\/documentation\/iden3\/networkerror"},"doc://Iden3/documentation/Iden3/NetworkError/localizedDescription":{"abstract":[],"title":"localizedDescription","url":"\/documentation\/iden3\/networkerror\/localizeddescription","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/Iden3\/documentation\/Iden3\/NetworkError\/localizedDescription"}}}